server:
  port: 8021

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yygh_hosp?serverTimeZone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    hikari:
      #      连接池名
      pool-name: DateHikariCP
      #      最小空闲连接数
      minimum-idle: 5
      #      空闲连接存活最大时间
      idle-timeout: 180000
      #      最大连接数，默认10
      maximum-pool-size: 10
      #      从连接池返回的连接自动提交
      auto-commit: true
      #      连接最大存活时间
      max-lifetime: 180000
      #      连接超时时间
      connection-timeout: 30000
      #      测试连接是否可用的查询语句
      connection-test-query: SELECT 1

mybatis-plus:
  type-aliases-package: com.model.yygh.model.hosp
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'admin'
      paths-to-match: '/admin/hosp'
      packages-to-scan:
        - com.model.yygh.model.hosp
        - com.service.hosp.controller
knife4j:
  enable: true
  setting:
    language: zh_cn
logging:
  level:
    root: warn
    sql: debug
    web: error
  file:
    path: /syt-logs/syt-log
